"""
DuarteOS MCP Server: Tool Forge
Cria e registra novas ferramentas MCP dinamicamente.
Agentes podem criar suas proprias tools quando precisam de capacidades novas.
Requer: pip install fastmcp
"""

from fastmcp import FastMCP
import json
import os
from datetime import datetime

mcp = FastMCP("tool-forge", instructions="Forge de ferramentas — cria, registra e gerencia tools customizadas")

TOOLS_DIR = os.path.join(os.getcwd(), ".claude", "mcp-servers", "custom-tools")
REGISTRY_FILE = os.path.join(TOOLS_DIR, "registry.json")


def _load_registry():
    """Carrega o registro de tools customizadas."""
    if os.path.exists(REGISTRY_FILE):
        with open(REGISTRY_FILE, "r") as f:
            return json.load(f)
    return {"tools": {}, "created": datetime.now().isoformat()}


def _save_registry(registry):
    """Salva o registro de tools."""
    os.makedirs(TOOLS_DIR, exist_ok=True)
    registry["updated"] = datetime.now().isoformat()
    with open(REGISTRY_FILE, "w") as f:
        json.dump(registry, f, indent=2)


@mcp.tool()
def create_tool(
    name: str,
    description: str,
    python_code: str,
    dependencies: str = "",
) -> str:
    """Cria uma nova tool Python e a registra.
    name: nome da tool (snake_case)
    description: o que a tool faz
    python_code: codigo Python da funcao (sem decoradores, so o corpo)
    dependencies: pip packages necessarios separados por virgula
    """
    os.makedirs(TOOLS_DIR, exist_ok=True)

    # Generate the tool file
    tool_file = os.path.join(TOOLS_DIR, f"{name}.py")

    # Wrap code in a proper FastMCP tool
    full_code = f'''"""
Auto-generated tool: {name}
{description}
Generated by DuarteOS Tool Forge
"""

{python_code}
'''

    with open(tool_file, "w") as f:
        f.write(full_code)

    # Register the tool
    registry = _load_registry()
    registry["tools"][name] = {
        "name": name,
        "description": description,
        "file": tool_file,
        "dependencies": [d.strip() for d in dependencies.split(",") if d.strip()],
        "created": datetime.now().isoformat(),
        "usage_count": 0,
    }
    _save_registry(registry)

    # Install dependencies if needed
    deps_msg = ""
    if dependencies:
        deps_list = [d.strip() for d in dependencies.split(",") if d.strip()]
        deps_msg = f" Dependencias necessarias: {', '.join(deps_list)}"

    return json.dumps({
        "created": name,
        "file": tool_file,
        "message": f"Tool '{name}' criada com sucesso.{deps_msg}",
        "next_step": f"Para usar, execute: python3 {tool_file}",
    })


@mcp.tool()
def list_tools() -> str:
    """Lista todas as tools customizadas registradas."""
    registry = _load_registry()

    tools = []
    for name, info in registry["tools"].items():
        tools.append({
            "name": name,
            "description": info["description"],
            "file": info["file"],
            "created": info["created"],
            "usage_count": info.get("usage_count", 0),
            "dependencies": info.get("dependencies", []),
        })

    tools.sort(key=lambda x: x["created"], reverse=True)
    return json.dumps({"total": len(tools), "tools": tools}, indent=2)


@mcp.tool()
def run_tool(name: str, args: str = "{}") -> str:
    """Executa uma tool customizada pelo nome.
    args: JSON string com argumentos para a tool
    """
    registry = _load_registry()

    if name not in registry["tools"]:
        available = list(registry["tools"].keys())
        return json.dumps({"error": f"Tool '{name}' nao encontrada", "available": available})

    tool_info = registry["tools"][name]
    tool_file = tool_info["file"]

    if not os.path.exists(tool_file):
        return json.dumps({"error": f"Arquivo da tool nao encontrado: {tool_file}"})

    import subprocess

    try:
        # Parse args
        tool_args = json.loads(args)
        args_str = json.dumps(tool_args)

        result = subprocess.run(
            ["python3", tool_file, args_str],
            capture_output=True, text=True, timeout=60,
            cwd=os.getcwd(),
        )

        # Increment usage count
        registry["tools"][name]["usage_count"] = tool_info.get("usage_count", 0) + 1
        _save_registry(registry)

        return json.dumps({
            "tool": name,
            "exit_code": result.returncode,
            "stdout": result.stdout[:10000],
            "stderr": result.stderr[:5000],
        })

    except subprocess.TimeoutExpired:
        return json.dumps({"error": f"Tool '{name}' excedeu timeout de 60s"})
    except Exception as e:
        return json.dumps({"error": str(e)})


@mcp.tool()
def delete_tool(name: str) -> str:
    """Remove uma tool customizada."""
    registry = _load_registry()

    if name not in registry["tools"]:
        return json.dumps({"error": f"Tool '{name}' nao encontrada"})

    tool_info = registry["tools"][name]

    # Remove file
    if os.path.exists(tool_info["file"]):
        os.remove(tool_info["file"])

    # Remove from registry
    del registry["tools"][name]
    _save_registry(registry)

    return json.dumps({"deleted": name, "remaining": len(registry["tools"])})


@mcp.tool()
def generate_mcp_server(
    server_name: str,
    tools_spec: str,
) -> str:
    """Gera um MCP server completo a partir de uma especificacao de tools.
    tools_spec: JSON array com [{name, description, params, returns, code}]
    """
    specs = json.loads(tools_spec)

    server_dir = os.path.join(os.getcwd(), ".claude", "mcp-servers", server_name)
    os.makedirs(server_dir, exist_ok=True)

    server_file = os.path.join(server_dir, "server.py")

    lines = [
        '"""',
        f'DuarteOS MCP Server: {server_name}',
        f'Auto-generated by Tool Forge',
        f'"""',
        '',
        'from fastmcp import FastMCP',
        'import json',
        '',
        f'mcp = FastMCP("{server_name}")',
        '',
    ]

    for tool_spec in specs:
        name = tool_spec["name"]
        desc = tool_spec.get("description", "")
        params = tool_spec.get("params", [])
        code = tool_spec.get("code", "    return 'Not implemented'")

        # Build function signature
        param_str = ", ".join(
            f"{p['name']}: {p.get('type', 'str')}" + (f" = {p['default']}" if 'default' in p else "")
            for p in params
        )

        lines.extend([
            '',
            '@mcp.tool()',
            f'def {name}({param_str}) -> str:',
            f'    """{desc}"""',
        ])

        for code_line in code.split('\n'):
            lines.append(f'    {code_line}')

        lines.append('')

    lines.extend([
        '',
        'if __name__ == "__main__":',
        '    mcp.run()',
    ])

    with open(server_file, 'w') as f:
        f.write('\n'.join(lines))

    # Add to registry
    registry = _load_registry()
    registry["tools"][f"server:{server_name}"] = {
        "name": server_name,
        "description": f"MCP Server com {len(specs)} tools",
        "file": server_file,
        "dependencies": ["fastmcp"],
        "created": datetime.now().isoformat(),
        "usage_count": 0,
        "type": "mcp_server",
    }
    _save_registry(registry)

    mcp_config = {
        server_name: {
            "command": "python3",
            "args": [f".claude/mcp-servers/{server_name}/server.py"]
        }
    }

    return json.dumps({
        "created": server_file,
        "tools_count": len(specs),
        "mcp_json_entry": mcp_config,
        "message": f"MCP Server '{server_name}' criado. Adicione ao .mcp.json para ativar.",
    }, indent=2)


if __name__ == "__main__":
    mcp.run()
